"""
Workflow state definitions for LangGraph SOC investigation.
"""

from typing import Any, Dict, List, Optional, TypedDict

from soc_analyst.agents.analyst.schemas import AnalystVerdict, ExtractedFacts
from soc_analyst.collector.models import NormalizedAlert


class InvestigationState(TypedDict):
    """State structure carried through the SOC analyst workflow graph.

    Attributes
    ----------
    alert : NormalizedAlert
        The normalized input security alert being investigated.
    facts : Optional[ExtractedFacts]
        The structured facts extracted from untrusted alert payload (Stage 4).
    triage_result : Optional[Dict[str, Any]]
        The initial classification (severity and type) based on facts.
    investigation_result : Optional[Dict[str, Any]]
        Evidence gathered from endpoint and network tools.
    threat_intel_result : Optional[Dict[str, Any]]
        Reputation indicators gathered from VirusTotal, AbuseIPDB, and AlienVault OTX.
    correlation_result : Optional[Dict[str, Any]]
        Cross-vendor log matching and DB history details.
    enriched_context : Dict[str, Any]
        Merged and synthesized context containing all gathered evidence (Phase 6 legacy compatibility).
    verdict : Optional[AnalystVerdict]
        The final verdict generated by the privileged Decision Analyst (Stage 5).
    errors : List[str]
        Operational errors encountered during graph traversal.
    is_blocked : bool
        True if the alert was blocked at the injection gate (Stage 3).
    """

    alert: NormalizedAlert
    facts: Optional[ExtractedFacts]
    triage_result: Optional[Dict[str, Any]]
    investigation_result: Optional[Dict[str, Any]]
    threat_intel_result: Optional[Dict[str, Any]]
    correlation_result: Optional[Dict[str, Any]]
    enriched_context: Dict[str, Any]
    verdict: Optional[AnalystVerdict]
    errors: List[str]
    is_blocked: bool
