network.host: 0.0.0.0
node.name: wazuh.indexer
cluster.initial_master_nodes:
  - wazuh.indexer

cluster.name: wazuh-cluster
node.max_local_storage_nodes: 3
path.data: /var/lib/wazuh-indexer
path.logs: /var/log/wazuh-indexer

plugins.security.ssl.http.pemcert_filepath: /usr/share/wazuh-indexer/certs/wazuh.indexer.pem
plugins.security.ssl.http.pemkey_filepath: /usr/share/wazuh-indexer/certs/wazuh.indexer-key.pem
plugins.security.ssl.http.pemtrustedcas_filepath: /usr/share/wazuh-indexer/certs/root-ca.pem
plugins.security.ssl.http.enabled: true
plugins.security.ssl.http.clientauth_mode: OPTIONAL
plugins.security.ssl.transport.pemcert_filepath: /usr/share/wazuh-indexer/certs/wazuh.indexer.pem
plugins.security.ssl.transport.pemkey_filepath: /usr/share/wazuh-indexer/certs/wazuh.indexer-key.pem
plugins.security.ssl.transport.pemtrustedcas_filepath: /usr/share/wazuh-indexer/certs/root-ca.pem
plugins.security.ssl.transport.enforce_hostname_verification: false

plugins.security.authcz.admin_dn:
  - CN=admin,OU=Wazuh,O=Wazuh,L=California,C=US
plugins.security.check_snapshot_restore_write_privileges: true
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.nodes_dn:
  - CN=wazuh.indexer,OU=Wazuh,O=Wazuh,L=California,C=US

plugins.security.restapi.roles_enabled:
  - all_access
  - security_rest_api_access

plugins.security.system_indices.enabled: true
plugins.security.system_indices.indices:
  - .plugins-ml-model
  - .plugins-ml-task
  - .opendistro-alerting-config
  - .opendistro-alerting-alert
  - .opendistro-anomaly-results
  - .opendistro-anomaly-detector
  - .opendistro-anomaly-checkpoints
  - .opendistro-anomaly-detection-state
  - .opendistro-reports-definitions
  - .opendistro-reports-instances
  - .opendistro-notifications-config
  - .opensearch-notebooks
  - .opensearch-observability
  - .plugins-ml-model-group
  - .plugins-flow-framework-config
  - .plugins-flow-framework-templates
  - .plugins-flow-framework-state

compatibility.override_main_response_version: true